version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo pre-build running npm install
      - npm install
  build:
    commands:
      - echo build phase
      - npm run build
  post_build:
    commands:
      - echo post-build phase
      - echo Build completed on `date`
      - echo Artifacts copied to S3

artifacts:
  files:
    - '**/*'
  name: mysouschef
